/**
 * @description       :
 * @author            : mamikals
 * @group             :
 * @last modified on  : 10-02-2023
 * @last modified by  : mamikals
 **/
public class CRM_OppgaveQueryList {
    public OppgaveStatuskategori statuskategori;
    public List<String> status;
    public List<String> tema;
    public List<String> oppgavetype;
    public String tildeltEnhetsnr;
    public boolean tildeltRessurs;
    public String tilordnetRessurs;
    public String behandlingstema;
    public String behandlingstype;
    public boolean erUtenMappe;
    public List<String> aktoerId;
    public List<String> journalpostId;
    public List<String> saksreferanse;
    public String opprettetAv;
    public String opprettetAvEnhetsnr;
    public Date aktivDatoFom;
    public Date aktivDatoTom;
    public Date opprettetFom;
    public Date opprettetTom;
    public Date ferdigstiltFom;
    public Date ferdigstiltTom;
    public Date fristFom;
    public Date fristTom;
    public String ikkeTidligereTilordnetRessurs;
    public List<String> orgnr;
    public String sorteringsrekkefolge;
    public String sorteringsfelt;
    public Integer returnLimit;
    public Integer offset;
}
