/**
 * @description       : 
 * @author            : mamikals
 * @group             : 
 * @last modified on  : 08-02-2023
 * @last modified by  : mamikals
**/
public class CRM_OppgaveQueryList {
    public OppgaveStatuskategori statuskategori;
    public List<String> status;
    public List<String> tema;
    public List<String> oppgavetype;
    public String tildeltEnhetsnr;
    public boolean tildeltRessurs;
    public String tilordnetRessurs;
    public String behandlingstema;
    public String behandlingstype;
    public boolean erUtenMappe;
    public List<String> aktoerId;
    public List<String> journalpostId;
    public List<String> saksreferanse;
    public String opprettetAv;
    public String opprettetAvEnhetsnr;
    public String aktivDatoFom;
    public String aktivDatoTom;
    public String opprettetFom;
    public String opprettetTom;
    public String ferdigstiltFom;
    public String ferdigstiltTom;
    public String fristFom;
    public String fristTom;
    public String ikkeTidligereTilordnetRessurs;
    public List<String> orgnr;
    public String sorteringsrekkefolge;
    public String sorteringsfelt;
    public Integer returnLimit;
    public Integer offset;
}